### ISSUE TITLE
Optimising AEAD

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#87]
I used to think RFC 7539 was over-engineered. I suspected their padding game were little more than some alignment game, which probably arisen from sub-par interfaces for the primitives. Interfaces that I was quite proud to generalise, if not simplify a bit.

Hem.

Turned out I was misguided and ignorant. First, I believed serialization and de-serialization took a negligible amount of time, compared to the heavy duty work. [Nope](https://github.com/LoupVaillant/Monocypher/commit/59a593dc76d7e792e5b4f314c89e8df7e39540f5). [Nope](https://github.com/LoupVaillant/Monocypher/commit/d51c2da361346bd5830fe38099fd47df6f11e57e). [Nope](https://github.com/LoupVaillant/Monocypher/commit/7e8cfb6b5e45c54213b7fd637fcda71e9ea9ab87). [Nope](https://github.com/LoupVaillant/Monocypher/commit/229c662e223535e85ac91697a5ef82e3a742e4bd). [Nope](https://github.com/LoupVaillant/Monocypher/commit/31d01f926d0092491ce5cccd07ffa294058c14e8). [Nope](https://github.com/LoupVaillant/Monocypher/commit/3bed29b92cf9bac76d21c7a5c2bd586adaa7756d). [Nope](https://github.com/LoupVaillant/Monocypher/commit/c8150fb58b8c45ede0930fcc2f33e4dff035f19f). The most impresive there was Poly1305, which became 5 times faster than it was. (De-)serialisation was a full blown *bottleneck*.

Second, I didn't know that the best way to optimise many such primitives, despite their structure, was to perform the good old "unroll then vectorise" trick. For Chacha20, processing 8 blocks at a time with AVX-2 instructions is *four times faster* than using AVX instructions for a single round. Despite Chacha20 being *designed* for single-round vectorisation. I wonder how fast full blown bit slicing would be… Poly1305 enjoys similar effects (Libsodium is 2.3 times faster than Monocypher).

Thus, the details of the AEAD construction have a significant impact on the performance of small and medium messages (I'm thinking 1-8 kilobytes). I've measured something between 10-30% slow-down. Not that we want Monocypher to reach ultimate performance. This would cost way too much code not to mention the portability nightmare, of which #85 gives a taste. But we do want to scale as needed. If some user start to notice Monocypher's suboptimal performance is hurting their power bill (they just overthrew Google or something), it would be nice to get that performance without breaking compatibility.

In this light, I have to admit RFC 7539 is actually pretty well thought out. The only real qualm I have with it is it's half assed nonce, which isn't long enough to support randomness *and* cuts the counter to a worryingly short length. It's padding scheme however is pretty much ideal:

- Wasting a whole Chacha block (64 bytes) to compute the authentication key instead of just 32-bytes is actually *faster* than keeping to 32 bytes. First, it tends to hit the fast path for de-serialization in typical implementations. Second, it facilitates streaming block by block, where the size of the blocks are powers of 2: by starting at a block boundary, we can ensure we never hit the slow serialisation path, _and_ we take full advantage of the "unroll-then-vectorise" scheme that is fond of multiple of 8 blocks, without odd remainders at the end.

   Assuming 4k blocks (a size that is dear to me personally because I'd like to implement a file system like encrypted archive), this alone speeds up the [fast version of Monocypher](https://github.com/LoupVaillant/Monocypher/tree/speed) by more than 15%. Smaller blocks (2k, 1k) are even more sensitive to this effect, and such sizes might be relevant to something like a chat application (where you would pad messages to multiples of 1kiB to reduce information leak).

- In terms of wasted computation, padding Poly1305 wastes at most 1 block. Considering this enables a 2.3 speedup on message boundaries when doing the same as Chacha20, and the fact that the encrypted buffers are generally distinct from the additional data, aligning the block at the beginning of the message makes sense.

   Of course, the padding means we now have to authenticate the length of both the additional data and the encrypted message. RFC 7539 have us covered there, using exactly 1 additional block to authenticate both lengths. 64 bits each should be plenty. Oh, and it removes the minor worry I had about authenticating the length of the additional data. Now it's all clean, even if that length is neither fixed nor self contained. That should simplify the manual a bit.

So I'm thinking of breaking compatibility. Again. This should fit the current API, we'll just have incompatible encryption and mac. The upside is, if some one wants to optimise this up to the heavens later, they can.

While we're at it, how about adding raw Chacha20 and IETF initialisation? The former can help with performance in some cases that don't require a random nonce, and the latter has test vectors. I still don't endorse 96-bit nonces, but at this point we might as well add it for completion's sake. I'm not sure yet. Maybe we could limit those alternate initialisation schemes to the incremental interface, and have the monolithic interface present a clear default?

**Comment by CuleX** [comment]
> So I'm thinking of breaking compatibility. Again. This should fit the current API, we'll just have incompatible encryption and mac. The upside is, if some one wants to optimise this up to the heavens later, they can.

This *is* a good excuse to break compatibility IMHO – though you'd better stop after 2.0.0 –, lest you lose credibility. Yes, this is a 2.0.0; you're breaking not only the API, but also the results that functions yield. We have a pretty tough call to make:

1. forever lug a legacy function around, or
2. make users decrypt and reencrypt any data stored at rest.

---

> [...] we might as well add it for completion's sake.

You're slowly but surely turning into libsodium.

> **Small.** Monocypher is under 1500 lines of code (counted with sloccount), small enough to allow comprehensive audits. The compiled library ranges from 45kB and 65kB depending on optimisation options.
>
> **Easy to use.** The API is small, consistent, and cannot fail on correct input.

I admit I've been slacking on the latter part with the incremental interfaces, though I believe those were fairly justified.

Think long and hard about whether you want to start heading down this slippery slope any further. I don't have any strong feelings, but I feel like Monocypher is losing its original UNIX-y sexiness

**Comment by LoupVaillant** [comment]
Ah. 2.0.0. Not good. You know what, I'll investigate this more closely, and use libsodium's primitives to see the ultimate impact on what is arguably the fastest implementation around—on x86_64 at least. Maybe it's not so bad. Maybe it is even worse.

If we do end up making that leap, I'd vote for keeping a legacy function around (and naming it something like `crypto_lock_aead_legacy()`, but only for the monolithic interface. The incremental interface are recent enough, I believe, not to have a huge impact on actual users just yet. That's a weak vote, though: compatibility was never Monocypher's goal, I don't want to be dragged too far down that path.

**Comment by LoupVaillant** [comment]
Okay, I've measured seriously now. I've pushed the relevant changes in the [speed branch](https://github.com/LoupVaillant/Monocypher/tree/speed) for reproducibility's sake. Most relevant are the results for libsodium. First the source code:

    void mono(uint8_t        mac[16],
              uint8_t       *cipher_text,
              const uint8_t  key[32],
              const uint8_t  nonce[24],
              const uint8_t *ad        , size_t ad_size,
              const uint8_t *plain_text, size_t text_size)
    {
        u8 auth_key[64];
        crypto_stream_chacha20(auth_key, 64, nonce, key);
        if (text_size >= 32) {
            // fast path for reasonable buffers
            for (int i = 0; i < 32; i += 8) {
                store64_le(cipher_text + i,
                           load64_le(auth_key + 32 + i) ^
                           load64_le(plain_text    + i));
            }
            crypto_stream_xchacha20_xor_ic(cipher_text + 32, plain_text,
                                           text_size - 32, nonce, 1, key);
        } else {
            // slow path for tiny buffers (not tested)
            FOR (i, 0, text_size) {
                cipher_text[i] = plain_text[i] ^ auth_key[i+32];
            }
        }
        crypto_onetimeauth_state ctx;
        crypto_onetimeauth_init  (&ctx, auth_key);
        crypto_onetimeauth_update(&ctx, ad         , ad_size    );
        crypto_onetimeauth_update(&ctx, cipher_text, text_size  );
        crypto_onetimeauth_final (&ctx, mac);
    }

    void ietf(uint8_t        mac[16],
              uint8_t       *cipher_text,
              const uint8_t  key[32],
              const uint8_t  nonce[24],
              const uint8_t *ad        , size_t ad_size,
              const uint8_t *plain_text, size_t text_size)
    {
        u8 auth_key[64];
        crypto_stream_chacha20(auth_key, 64, nonce, key);
        crypto_stream_xchacha20_xor_ic(cipher_text, plain_text, text_size,
                                       nonce, 1, key);
        u8 padding[15] = {0};
        u8 sizes  [16];
        unsigned p_ad_size   = (-  ad_size) & 15;
        unsigned p_text_size = (-text_size) & 15;
        store64_le(sizes    ,   ad_size);
        store64_le(sizes + 8, text_size);

        crypto_onetimeauth_state ctx;
        crypto_onetimeauth_init  (&ctx, auth_key);
        crypto_onetimeauth_update(&ctx, ad         , ad_size    );
        crypto_onetimeauth_update(&ctx, padding    , p_ad_size  );
        crypto_onetimeauth_update(&ctx, cipher_text, text_size  );
        crypto_onetimeauth_update(&ctx, padding    , p_text_size);
        crypto_onetimeauth_update(&ctx, sizes      , 16         );
        crypto_onetimeauth_final (&ctx, mac);
    }

I've quickly put together 2 AEAD schemes. I've chosen the monolithic interface for speed and simplicity. I've tried to optimise as best I could. I've ignored any wiping. The `mono` function is compatible with the current Monocypher implementation (unless of course there's a bug). As you can see, it is quite convoluted, since it works around the limitation of the libsodium API. Note that Monocypher has to do the same convolutions in its own code, see my patches about optimising loading code. The `ietf` functions does IETF style padding. Simpler than I expected from the specs, I have to say.

Now I've measured those functions with various buffer sizes (all powers of 2 since that's what an implementer would use to optimise stuff at various levels):


    Auth'd encryption  :  1135 megabytes  per second
      4k   blocks      :  1000 megabytes  per second
      4k   blocks mono :   894 megabytes  per second

      2k   blocks      :   903 megabytes  per second
      2k   blocks mono :   755 megabytes  per second

      1k   blocks      :   749 megabytes  per second
      1k   blocks mono :   566 megabytes  per second

      512b blocks      :   559 megabytes  per second
      512b blocks mono :   379 megabytes  per second

As you can see the slow down triggered by my API is quite brutal. The fast branch of Monocypher is even more affected (that with not having quad rounds). And even with a hardware implementation where octo/quad rounds would not matter, there's no escaping the fact that Chacha20 is fundamentally a block hash function. Misaligned buffers are bound to at least complicate things down the road.

Fun fact: the general slow down is mostly Poly1305's fault. This primitive seems to have a high startup time for some reason. We can see that in the Poly1305 tests. Monocypher is less affected, but it hardly matters since it was slower to begin with.

Note that I haven't tested non-null additional data. Given what I know about filling buffers, I expect similar slow downs if there's no padding.

Conclusion: there will be a 2.0.0. This is a sad day for Monocypher, I didn't expect that. I wanted to save that kind of bump for major changes like post-quantum crypto or something. Turned out the only thing I designed myself in the whole library was flawed. Oh well. I wouldn't have blindly copied an existing design anyway, so…

---

Now, about handling legacy. Here's my current opinion (different from a few hours ago, by the way): I think we should throw away all the legacy, and support only one true cipher. For backward compatibility, I shall maintain *both* 1.1.0 and 2.0.0. Shouldn't be a problem as long as Monocypher stays focused. With any luck, we'll won't have to go beyond 2.0.3 (and 1.1.3).

I think I will keep and expand the speed experiments in the future. But that branch won't have the same goal as the mainline at all: forget about deployment or portability, this will be only for raw speed on bleeding edge x86_64 with recent GCC or Clang.

How does that sound?

**Comment by CuleX** [comment]
> I think I will keep and expand the speed experiments in the future. But that branch won't have the same goal as the mainline at all: forget about deployment or portability, this will be only for raw speed on bleeding edge x86_64 with recent GCC or Clang.
>
> How does that sound?

Like definitely not like Monocypher. I'd suggest you move the entire thing into something called "Duocipher" or something, though hosting alongside Monocypher is fine.

**Comment by LoupVaillant** [comment]
I was also asking about handling legacy. Does maintaining 2 branches à la Python sounds bearable, or do you anticipate difficulties down the road?

**Comment by LoupVaillant** [comment]
By the way, I figured out a migration path for the monolithic interface: modify `crypto_unlock_aead()` so that it tries both schemes, the old *and* the new. If one fails, try the other. If both fail, error out like before. That's dirty and not worthy of 2.0.0, but if some user really *really* need backward compatibility, that's possible.

The incremental interface however isn't so lucky. A similar fix for this would be more intrusive. Hopefully that's not really a problem, considering how young 1.1.0 is.

**Comment by CuleX** [comment]
> I was also asking about handling legacy. Does maintaining 2 branches à la Python sounds bearable, or do you anticipate difficulties down the road?

Please look at the Python 2/Python 3 split. It's been almost a decade and Python 2 still isn't dying. The only good news is that if you're changing Monocypher 1.1, you've probably very gravely broken things. I expect there won't be anything to backport.

That said, you don't really have a choice here. Either you break all messages at rest or you'll forever maintain two branches. The former is arguably not an option.

Lessons learned: Put the algorithm name in the function for the new AEAD functions, drop the \*lock\* and \*sign\* stuff altogether. Why? Because of this. You already did that with argon2i and blake2 anyway.

---

> By the way, I figured out a migration path for the monolithic interface: modify `crypto_unlock_aead()` so that it tries both schemes, the old and the new. If one fails, try the other. If both fail, error out like before. That's dirty and not worthy of 2.0.0, but if some user really really need backward compatibility, that's possible.
>
> The incremental interface however isn't so lucky. A similar fix for this would be more intrusive. Hopefully that's not really a problem, considering how young 1.1.0 is.

So on a malformed message, you're now looking at roughly half the performance from before because it has to try two algorithms?

If it's that bad, can you just undo the 1.1.0 release? You seem very convinced it was a mistake to have released it.

**Comment by LoupVaillant** [comment]
> Lessons learned: Put the algorithm name in the function for the new AEAD functions, drop the *lock* and *sign* stuff altogether.

This would turn `crypto_lock` into `crypto_chacha20_poly1305_ietf`, and we haven't put the `aead` and incremental suffixes yet. I don't think I could bear it. Besides, I still want to provide a clear default. If I start to lug 2 functions with 2 slightly different constructions, and none has a name that tell the users "use me", they are going to be confused about which one they really want.

What's really missing is a specification of the protocol in the manual. Users should know what they are using without having to dig up the source code. Libsodium has a similar problem apparently.

> If it's that bad, can you just undo the 1.1.0 release? You seem very convinced it was a mistake to have released it.

If it was, 1.0.0 was the real mistake. 1.1.0 is merely compatible. We do have alternatives, though:

* I can maintain 2 branches, hoping that 1.1.0 will never ever have any reason to change (the manual might be tweaked here and there).
* I can disavow past releases and tell everyone to re-encrypt their data at rest.
* I can forever lug a set of legacy functions. I can even put those functions in separate files, like I did SHA-512.

Then there's the 2.0.0 vs 1.2.0 thing. The only incompatibility between the IETF way and the old way is the content of the encrypted message and the content of the tag. The API, including buffer lengths, stay the same. Upgrading for data in transit is no problem as long as everyones update their software —which by the way cannot possibly be more than a couple months old. It's such a small change, I really don't like bumping the major version number just for this. Data at rest is of course more problematic.

But I have to ask: how many users do we have? I count 165 stars and 13 forks at the moment. Libsodium by comparison has over 5000 stars and 750 forks. How many applications and utilities are already written with Monocypher? How many are used by anyone other than their maker? I won't bet my hat, but I wouldn't be surprised by a grand total of zero for both. Monocypher has been publicly released only 7 months ago.

Another problem with 2.0.0 is the signalling: "2.0.0" looks less stable than "1.1.0", even though it definitely won't be. Major increments would signal a significant overhaul of the API, while in fact it is just a little tweak. An incompatible tweak, but still.

**Comment by CuleX** [comment]
> * I can maintain 2 branches, hoping that 1.1.0 will never ever have any reason to change (the manual might be tweaked here and there).
> * I can disavow past releases and tell everyone to re-encrypt their data at rest.
> * I can forever lug a set of legacy functions. I can even put those functions in separate files, like I did SHA-512.

I'm leaning towards option 2, bumping the version and pissing off – at most – a dozen of users. Thankfully, nobody *actually* packaged Monocypher, at least to my knowledge. It's "only" in AUR for Arch.

Two branches sounds like a pain, but I'd be fine with it if there's any actual user chirping in and requesting it be maintained. Even backports of new things should be fairly trivial.

Legacy functions make me worry about starting a precedent, just in case this happens again. Something tells me this won't have been the last time.

> But I have to ask: how many users do we have? I count 165 stars and 13 forks at the moment. Libsodium by comparison has over 5000 stars and 750 forks. How many applications and utilities are already written with Monocypher? How many are used by anyone other than their maker?

I do use it for argon2i in [lm](https://github.com/CuleX/lm), but that's more of a toy than anything. Since there's no real way to tell how many users there are, I doubt we'll ever know for sure. Plus there *have* been bindings to some scripting languages, I can only assume people did that for their own benefit.

> Another problem with 2.0.0 is the signalling: "2.0.0" looks less stable than "1.1.0", even though it definitely won't be. Major increments would signal a significant overhaul of the API, while in fact it is just a little tweak. An incompatible tweak, but still.

As Larry Ellison said: "[The very first version was Oracle version 2. We knew no one would want to buy version 1.](http://www.businessinsider.com/the-cia-made-larry-ellison-a-billionaire-2014-9?international=true&r=US&IR=T)"
